# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/3/
Content-Type: application/json

{  
  "name": "ESP64",
  "description": "Перенес датчик на балкон",
  "measurements": []

}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 28.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/3/
Content-Type: application/json

###
# Выдается список с краткой информацией по датчикам
GET {{baseUrl}}/list/
Content-Type: application/json
